[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EAgent"
authors = [{name = "Yu Zhou", email = "bryanzhou008@ucla.edu"}]
dynamic = ["version", "description"]